from django.urls import path

from .views import (
    AdminAnalyticsView,
    AdminAuditLogView,
    AdminConfigView,
    AdminDailyActivityView,
    AdminDialogueTemplatesView,
    AdminFacilityDetailView,
    AdminFacilitiesView,
    AdminModelMetricsView,
    AdminRetrainModelView,
    AdminTopQuestionsView,
    AdminUserActivityView,
    AdminUserDetailView,
    AdminUsersView,
    AnalyzeCaseView,
    AnalysisStatusView,
    DetectLanguageView,
    SupportedLanguagesView,
    AnalysisStatusSSEView,
    ChatAnalyzeView,
    ChatHistoryView,
    ChatSessionListCreateView,
    ChatSessionMessagesView,
    CookieTokenRefreshView,
    EmergencyContactsView,
    ExportChatHistoryView,
    ExportProfileView,
    HealthView,
    LocationDirectionsView,
    LocationNearbyView,
    LoginView,
    LogoutView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileView,
    QuickPromptsView,
    RegisterView,
    ResendVerificationEmailView,
    SocialLoginView,
    SocialProvidersView,
    VerifyEmailView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("quick-prompts/", QuickPromptsView.as_view(), name="quick-prompts"),
    path("analyze/", AnalyzeCaseView.as_view(), name="analyze"),
    path("analyze/<int:case_id>/", AnalysisStatusView.as_view(), name="analyze-status"),
    path("analyze/<int:case_id>/stream/", AnalysisStatusSSEView.as_view(), name="analyze-status-sse"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/refresh/", CookieTokenRefreshView.as_view(), name="auth-refresh"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/verify-email/", VerifyEmailView.as_view(), name="auth-verify-email"),
    path("auth/resend-verification/", ResendVerificationEmailView.as_view(), name="auth-resend-verification"),
    path("auth/password-reset/", PasswordResetRequestView.as_view(), name="auth-password-reset"),
    path("auth/password-reset/confirm/", PasswordResetConfirmView.as_view(), name="auth-password-reset-confirm"),
    path("auth/social/login/", SocialLoginView.as_view(), name="auth-social-login"),
    path("auth/social/providers/", SocialProvidersView.as_view(), name="auth-social-providers"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("chat/sessions/", ChatSessionListCreateView.as_view(), name="chat-sessions"),
    path("chat/sessions/<int:session_id>/messages/", ChatSessionMessagesView.as_view(), name="chat-messages"),
    path("chat/sessions/<int:session_id>/analyze/", ChatAnalyzeView.as_view(), name="chat-analyze"),
    path("chat/history/", ChatHistoryView.as_view(), name="chat-history"),
    path("chat/export/", ExportChatHistoryView.as_view(), name="chat-export"),
    path("location/nearby/", LocationNearbyView.as_view(), name="location-nearby"),
    path("location/directions/", LocationDirectionsView.as_view(), name="location-directions"),
    path("location/emergency/", EmergencyContactsView.as_view(), name="location-emergency"),
    path("admin/users/", AdminUsersView.as_view(), name="admin-users"),
    path("admin/users/<int:user_id>/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("admin/facilities/", AdminFacilitiesView.as_view(), name="admin-facilities"),
    path("admin/facilities/<int:facility_id>/", AdminFacilityDetailView.as_view(), name="admin-facility-detail"),
    path("admin/analytics/", AdminAnalyticsView.as_view(), name="admin-analytics"),
    path("admin/config/", AdminConfigView.as_view(), name="admin-config"),
    path("admin/audit-log/", AdminAuditLogView.as_view(), name="admin-audit-log"),
    path("admin/dialogue-templates/", AdminDialogueTemplatesView.as_view(), name="admin-dialogue-templates"),
    path("admin/model-metrics/", AdminModelMetricsView.as_view(), name="admin-model-metrics"),
    path("admin/retrain/", AdminRetrainModelView.as_view(), name="admin-retrain"),
    path("admin/user-activity/", AdminUserActivityView.as_view(), name="admin-user-activity"),
    path("admin/daily-activity/", AdminDailyActivityView.as_view(), name="admin-daily-activity"),
    path("admin/top-questions/", AdminTopQuestionsView.as_view(), name="admin-top-questions"),
    path("detect-language/", DetectLanguageView.as_view(), name="detect-language"),
    path("supported-languages/", SupportedLanguagesView.as_view(), name="supported-languages"),
    path("export/profile/", ExportProfileView.as_view(), name="export-profile"),
]
