# Generated by Django 5.2.11 on 2026-02-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom_text', models.TextField()),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='case_uploads/')),
                ('consent_given', models.BooleanField(default=False)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='received', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('place_id', models.CharField(blank=True, max_length=128)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('maps_url', models.URLField(blank=True)),
                ('source', models.CharField(default='google_places', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='guidance.casesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='InferenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_predictions', models.JSONField(blank=True, default=list)),
                ('image_predictions', models.JSONField(blank=True, default=list)),
                ('fused_predictions', models.JSONField(blank=True, default=list)),
                ('text_confidence', models.FloatField(blank=True, null=True)),
                ('image_confidence', models.FloatField(blank=True, null=True)),
                ('fusion_confidence', models.FloatField(blank=True, null=True)),
                ('confidence_band', models.CharField(default='low', max_length=16)),
                ('text_model_version', models.CharField(default='text-v1', max_length=64)),
                ('image_model_version', models.CharField(default='image-v1', max_length=64)),
                ('fusion_version', models.CharField(default='fusion-v1', max_length=64)),
                ('uncertainty', models.FloatField(default=1.0)),
                ('disagreement', models.FloatField(default=0.0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inference', to='guidance.casesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=16)),
                ('severity_component', models.FloatField(default=0.0)),
                ('redflag_component', models.FloatField(default=0.0)),
                ('vulnerability_component', models.FloatField(default=0.0)),
                ('uncertainty_component', models.FloatField(default=0.0)),
                ('disagreement_component', models.FloatField(default=0.0)),
                ('recommendation_text', models.TextField()),
                ('disclaimer_text', models.TextField()),
                ('needs_urgent_care', models.BooleanField(default=False)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='guidance.casesubmission')),
            ],
        ),
    ]
